### ISSUE TITLE
ERROR: LoadError: ArgumentError: Package VDPTag not found in current path: - Run `import Pkg; Pkg.add("VDPTag")` to install the VDPTag package.

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [zsunberg/VDPTag.jl#1]
Hey Zach,

I am about to start updating your code to Julia 1.0 and I got the above error. I verified that VDPTag is in my Julia/dev folder and that the path is being pushed in my startup file. Any suggestions as to how to fix this?

**Comment by ChandlerKilpatrick1** [comment]
This error occurs when running `basic.jl`.

**Comment by ChandlerKilpatrick1** [comment]
This fixed my issue: 

```
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag")
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag/src")
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag/test")
```

**Comment by ChandlerKilpatrick1** [comment]
This fixed my issue: 

```
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag")
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag/src")
push!(LOAD_PATH, "/Users/chandlerkilpatrick/.julia/dev/VDPTag/test")
```

**Comment by zsunberg** [comment]
Hi @ChandlerKilpatrick1 , Thanks for working on upgrading it!!

The new package system is designed so that we should never have to modify `LOAD_PATH` manually :)

The correct way to fix it is to create a Project.toml file to replace REQUIRE and test/REQUIRE (let me know if you can't figure out how to do this). Then I prefer this way to test it:

```
$ cd ~/.julia/dev/VDPTag
$ julia --project # starts julia with the VDPTag project activated

julia> # press ] to go into Pkg mode

(VDPTag) pkg> test
```

**Comment by logankilpatrick** [comment]
Ah! That makes sense. Running VDPTag via the tests is the best way to actually run the Van Der Pol Tag scenarios correct?

**Comment by zsunberg** [comment]
Hmmm... which "Van Der Pol Tag scenarios" are you talking about? Are you talking about for the POMCPOW paper? Those tests are here: https://github.com/zsunberg/ContinuousPOMDPTreeSearchExperiments.jl/blob/master/icaps_2018/vdpbarrier_table.jl

The tests in this package just test whether this package works.

**Comment by zsunberg** [comment]
Actually it looks like I started using this package: https://github.com/zsunberg/VDPTag2.jl

**Comment by ChandlerKilpatrick1** [comment]
I did the following: 

```
(v0.7) pkg> activate VDPTag2

(VDPTag2) pkg> test
ERROR: trying to test unnamed project

(VDPTag2) pkg> 

```

**Comment by ChandlerKilpatrick1** [comment]
I am running Julia from the Repl and not the cmd line.

**Comment by ChandlerKilpatrick1** [comment]
and when I do `using VDPTag2` I get 
```
WARNING: importing deprecated binding Base.isnull into VDPTag2.
ERROR: LoadError: ArgumentError: Package VDPTag2 does not have MCTS in its dependencies:
- If you have VDPTag2 checked out for development and have
  added MCTS as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with VDPTag2
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:830
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:319 [inlined]
 [7] eval(::Expr) at ./client.jl:399
 [8] top-level scope at ./none:3
in expression starting at /Users/chandlerkilpatrick/.julia/dev/VDPTag2/src/VDPTag2.jl:17
ERROR: Failed to precompile VDPTag2 [c65614a0-9508-5473-a3de-3c59c024df67] to /Users/chandlerkilpatrick/.julia/compiled/v0.7/VDPTag2/pMhog.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

**Comment by ChandlerKilpatrick1** [comment]
I created the Project.toml file and ran it with REQUIRE copied in and I ran it blank but got the same error as above.

**Comment by zsunberg** [comment]
Hi @ChandlerKilpatrick1,

The Project.toml file uses a format different from REQUIRE. Look in the Pkg.jl documentation for more details. I think the easiest way to create it is by activating the project in the current directory and using the `add` command in package mode to add the packages from REQUIRE to it. Also see https://discourse.julialang.org/t/convert-require-to-project-toml-and-manifest-toml/17775.

Regarding the error, the isnull function was moved to https://github.com/JuliaAttic/Nullables.jl in version 0.7, so you have to import that package to use it.

**Comment by logankilpatrick** [comment]
https://julialang.github.io/Pkg.jl/v1/creating-packages/#**5.**-Creating-Packages-1

You can also do this to auto-generate a `Project.toml` from a require file.
